[package]
name = "nordvpn"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", features = ["macros"] } 
chrono = "0.4.38"
clap = { version = "4.5.22", features = ["derive"] } 
dns-lookup = "2.0.4"
env_logger = "0.11.5"
gethostname = "0.5"
http = "1.2"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
local-ip-address = "0.6"
log = "0.4.22"
pin-project-lite = "*"
reqwest = { version = "0.12", features = ["json"] }
route-recognizer = "0.3.1"
serde = { version = "1.0.120", features = ["default"] }
serde_derive = "1.0"
serde_json = { version = "1.0.120", features = ["default"] }
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "*"
uuid = { version = "1.0", features = ["v4"] }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-axum = "0.1"
utoipa-swagger-ui = { version = "*" ,features = ["axum"] }

